2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Configure stats pid to 25495
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Loading settings from /Users/felixwidmann/.config/wandb/settings
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Loading settings from /Users/felixwidmann/Documents/DHBW/ML_Assignment/data/wandb/settings
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-08 15:01:16,020 INFO    MainThread:25495 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-08 15:01:16,021 INFO    MainThread:25495 [wandb_init.py:_log_setup():520] Logging user logs to /Users/felixwidmann/Documents/DHBW/ML_Assignment/data/wandb/run-20240608_150116-forwz1p7/logs/debug.log
2024-06-08 15:01:16,021 INFO    MainThread:25495 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/felixwidmann/Documents/DHBW/ML_Assignment/data/wandb/run-20240608_150116-forwz1p7/logs/debug-internal.log
2024-06-08 15:01:16,021 INFO    MainThread:25495 [wandb_init.py:init():560] calling init triggers
2024-06-08 15:01:16,021 INFO    MainThread:25495 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-08 15:01:16,021 INFO    MainThread:25495 [wandb_init.py:init():610] starting backend
2024-06-08 15:01:16,021 INFO    MainThread:25495 [wandb_init.py:init():614] setting up manager
2024-06-08 15:01:16,027 INFO    MainThread:25495 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-08 15:01:16,028 INFO    MainThread:25495 [wandb_init.py:init():622] backend started and connected
2024-06-08 15:01:16,039 INFO    MainThread:25495 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-06-08 15:01:16,039 INFO    MainThread:25495 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-08 15:01:16,039 INFO    MainThread:25495 [wandb_init.py:init():711] updated telemetry
2024-06-08 15:01:16,041 INFO    MainThread:25495 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-08 15:01:16,426 WARNING MsgRouterThr:25495 [router.py:message_loop():77] message_loop has been closed
2024-06-08 15:01:16,426 ERROR   MainThread:25495 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-06-08 15:01:16,426 ERROR   MainThread:25495 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/felixwidmann/Documents/DHBW/ML_Assignment/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/felixwidmann/Documents/DHBW/ML_Assignment/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
